/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo dictionary1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Back"),
    N_("go back (search history)"),
    (gpointer) on_back1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-go-back",
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Forward"),
    N_("go forward (search history)"),
    (gpointer) on_forward1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-go-forward",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Search"),
    N_("start search for given word"),
    (gpointer) on_search1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-find",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (file_quit_activated, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menuitem2_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PASTE_ITEM (file_paste_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Mini-Mode"),
    N_("switch to small window size"),
    (gpointer) on_mini_mode1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Window-Mode"),
    N_("swizch to normal window size"),
    (gpointer) on_window_mode1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menuitem4_menu_uiinfo[] =
{
  GNOMEUIINFO_HELP ("gnome-ding"),
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_info1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("Dictionary"),
    NULL,
    dictionary1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_MENU_EDIT_TREE (menuitem2_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (view1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (menuitem4_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_gnome_ding (void)
{
  GtkWidget *gnome_ding;
  GdkPixbuf *gnome_ding_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *hbox1;
  GtkWidget *button1;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image8;
  GtkWidget *button_back;
  GtkWidget *button_vor;
  GtkWidget *image9;
  GtkWidget *label_searchword;
  GtkWidget *suchinput;
  GtkWidget *selection;
  GtkWidget *selection_combo;
  GtkWidget *submitbutton;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *eventbox1;
  AtkObject *atko;
  GtkWidget *image7;
  GtkWidget *output;
  GtkWidget *viewport1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport2;
  GtkWidget *scrolledwindow2;
  GtkWidget *list;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  gnome_ding = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (gnome_ding, "gnome_ding");
  gtk_window_set_title (GTK_WINDOW (gnome_ding), _("gnome ding"));
  gnome_ding_icon_pixbuf = create_pixbuf ("gnome-ding/gnome-ding.png");
  if (gnome_ding_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (gnome_ding), gnome_ding_icon_pixbuf);
      gdk_pixbuf_unref (gnome_ding_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gnome_ding), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_set_name (menubar1_uiinfo[0].widget, "dictionary1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[0].widget, "back1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[1].widget, "forward1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[2].widget, "separator2");

  gtk_widget_set_name (dictionary1_menu_uiinfo[3].widget, "search1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[4].widget, "preferences1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[5].widget, "separator1");

  gtk_widget_set_name (dictionary1_menu_uiinfo[6].widget, "beenden1");

  gtk_widget_set_name (menubar1_uiinfo[1].widget, "menuitem2");

  gtk_widget_set_name (menuitem2_menu_uiinfo[0].widget, "einf__gen1");

  gtk_widget_set_name (menubar1_uiinfo[2].widget, "view1");

  gtk_widget_set_name (view1_menu_uiinfo[0].widget, "mini_mode1");

  gtk_widget_set_name (view1_menu_uiinfo[1].widget, "window_mode1");

  gtk_widget_set_name (menubar1_uiinfo[3].widget, "menuitem4");

  gtk_widget_set_name (menuitem4_menu_uiinfo[1].widget, "info1");

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 2);

  button1 = gtk_button_new ();
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 4);
  gtk_widget_set_sensitive (button1, FALSE);
  gtk_tooltips_set_tip (tooltips, button1, _("go back (search history)"), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button1), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image8, "image8");
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox4), image8, FALSE, FALSE, 0);

  button_back = gtk_label_new_with_mnemonic ("");
  gtk_widget_set_name (button_back, "button_back");
  gtk_widget_show (button_back);
  gtk_box_pack_start (GTK_BOX (hbox4), button_back, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (button_back), GTK_JUSTIFY_LEFT);

  button_vor = gtk_button_new ();
  gtk_widget_set_name (button_vor, "button_vor");
  gtk_widget_show (button_vor);
  gtk_box_pack_start (GTK_BOX (hbox1), button_vor, FALSE, FALSE, 4);
  gtk_widget_set_sensitive (button_vor, FALSE);
  gtk_tooltips_set_tip (tooltips, button_vor, _("go forward (search history)"), NULL);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image9, "image9");
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button_vor), image9);

  label_searchword = gtk_label_new_with_mnemonic (_("_Word:"));
  gtk_widget_set_name (label_searchword, "label_searchword");
  gtk_widget_show (label_searchword);
  gtk_box_pack_start (GTK_BOX (hbox1), label_searchword, FALSE, FALSE, 4);
  gtk_label_set_justify (GTK_LABEL (label_searchword), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label_searchword), 5, 0);

  suchinput = gtk_entry_new ();
  gtk_widget_set_name (suchinput, "suchinput");
  gtk_widget_show (suchinput);
  gtk_box_pack_start (GTK_BOX (hbox1), suchinput, TRUE, TRUE, 4);
  gtk_tooltips_set_tip (tooltips, suchinput, _("specify the search string"), NULL);
  gtk_entry_set_activates_default (GTK_ENTRY (suchinput), TRUE);

  selection = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (selection)->popwin),
                     "GladeParentKey", selection);
  gtk_widget_set_name (selection, "selection");
  gtk_widget_show (selection);
  gtk_box_pack_start (GTK_BOX (hbox1), selection, TRUE, TRUE, 4);

  selection_combo = GTK_COMBO (selection)->entry;
  gtk_widget_set_name (selection_combo, "selection_combo");
  gtk_widget_show (selection_combo);
  gtk_tooltips_set_tip (tooltips, selection_combo, _("select the dictinory"), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (selection_combo), FALSE);
  gtk_entry_set_text (GTK_ENTRY (selection_combo), _(" "));

  submitbutton = gtk_button_new ();
  gtk_widget_set_name (submitbutton, "submitbutton");
  gtk_widget_show (submitbutton);
  gtk_box_pack_start (GTK_BOX (hbox1), submitbutton, FALSE, FALSE, 4);
  gtk_tooltips_set_tip (tooltips, submitbutton, _("start search for given word"), NULL);
  gtk_widget_add_accelerator (submitbutton, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (submitbutton), GTK_RELIEF_HALF);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (submitbutton), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("_Search"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox1, "eventbox1");
  gtk_widget_show (eventbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox1, _("minimode/winmode"), NULL);

  image7 = create_pixmap (gnome_ding, "gnome-ding/gnome-ding24.png");
  gtk_widget_set_name (image7, "image7");
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (eventbox1), image7);
  gtk_misc_set_alignment (GTK_MISC (image7), 0, 0);
  gtk_misc_set_padding (GTK_MISC (image7), 5, 0);

  output = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (output, "output");
  gtk_widget_show (output);
  gtk_box_pack_start (GTK_BOX (vbox1), output, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (output), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (output), viewport1);
  gtk_container_set_border_width (GTK_CONTAINER (viewport1), 2);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_NONE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (viewport1), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport2, "viewport2");
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport2);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport2), GTK_SHADOW_NONE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (viewport2), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  list = gtk_tree_view_new ();
  gtk_widget_set_name (list, "list");
  gtk_widget_show (list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), list);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gnome_ding, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_vor, "clicked",
                    G_CALLBACK (on_button_vor_clicked),
                    NULL);
  g_signal_connect ((gpointer) submitbutton, "clicked",
                    G_CALLBACK (on_submitbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) eventbox1, "button_press_event",
                    G_CALLBACK (on_eventbox1_button_press_event),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label_searchword), suchinput);

  atko = gtk_widget_get_accessible (eventbox1);
  atk_object_set_description (atko, _("gnome-ding Homepage: http://www.grawert.net/software/"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gnome_ding, gnome_ding, "gnome_ding");
  GLADE_HOOKUP_OBJECT (gnome_ding, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gnome_ding, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (gnome_ding, menubar1_uiinfo[0].widget, "dictionary1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[0].widget, "back1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[1].widget, "forward1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[2].widget, "separator2");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[3].widget, "search1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[4].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[5].widget, "separator1");
  GLADE_HOOKUP_OBJECT (gnome_ding, dictionary1_menu_uiinfo[6].widget, "beenden1");
  GLADE_HOOKUP_OBJECT (gnome_ding, menubar1_uiinfo[1].widget, "menuitem2");
  GLADE_HOOKUP_OBJECT (gnome_ding, menuitem2_menu_uiinfo[0].widget, "einf__gen1");
  GLADE_HOOKUP_OBJECT (gnome_ding, menubar1_uiinfo[2].widget, "view1");
  GLADE_HOOKUP_OBJECT (gnome_ding, view1_menu_uiinfo[0].widget, "mini_mode1");
  GLADE_HOOKUP_OBJECT (gnome_ding, view1_menu_uiinfo[1].widget, "window_mode1");
  GLADE_HOOKUP_OBJECT (gnome_ding, menubar1_uiinfo[3].widget, "menuitem4");
  GLADE_HOOKUP_OBJECT (gnome_ding, menuitem4_menu_uiinfo[1].widget, "info1");
  GLADE_HOOKUP_OBJECT (gnome_ding, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gnome_ding, button1, "button1");
  GLADE_HOOKUP_OBJECT (gnome_ding, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gnome_ding, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gnome_ding, image8, "image8");
  GLADE_HOOKUP_OBJECT (gnome_ding, button_back, "button_back");
  GLADE_HOOKUP_OBJECT (gnome_ding, button_vor, "button_vor");
  GLADE_HOOKUP_OBJECT (gnome_ding, image9, "image9");
  GLADE_HOOKUP_OBJECT (gnome_ding, label_searchword, "label_searchword");
  GLADE_HOOKUP_OBJECT (gnome_ding, suchinput, "suchinput");
  GLADE_HOOKUP_OBJECT (gnome_ding, selection, "selection");
  GLADE_HOOKUP_OBJECT (gnome_ding, selection_combo, "selection_combo");
  GLADE_HOOKUP_OBJECT (gnome_ding, submitbutton, "submitbutton");
  GLADE_HOOKUP_OBJECT (gnome_ding, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gnome_ding, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gnome_ding, image1, "image1");
  GLADE_HOOKUP_OBJECT (gnome_ding, label1, "label1");
  GLADE_HOOKUP_OBJECT (gnome_ding, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (gnome_ding, image7, "image7");
  GLADE_HOOKUP_OBJECT (gnome_ding, output, "output");
  GLADE_HOOKUP_OBJECT (gnome_ding, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gnome_ding, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gnome_ding, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (gnome_ding, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gnome_ding, list, "list");
  GLADE_HOOKUP_OBJECT (gnome_ding, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (gnome_ding, tooltips, "tooltips");

  gtk_widget_grab_focus (suchinput);
  gtk_window_add_accel_group (GTK_WINDOW (gnome_ding), accel_group);

  return gnome_ding;
}

GtkWidget*
create_about_gnome_ding (void)
{
  const gchar *authors[] = {
    "Heiko Abraham <abrahamh@web.de>",
    NULL
  };
  const gchar *documenters[] = {
    "Heiko Abraham <abrahamh@web.de>",
    NULL
  };
  gchar *translators = "Heiko Abraham <abrahamh@web.de>";
  GdkPixbuf *about_gnome_ding_logo_pixbuf;
  GtkWidget *about_gnome_ding;

  about_gnome_ding_logo_pixbuf = create_pixbuf ("gnome-ding/gnome-ding.png");
  about_gnome_ding = gnome_about_new ("gnome-ding", VERSION,
                        _("(c) 2003 Heiko Abraham"),
                        _("A translation- and spellchecking program for single words, inspired by \"ding\" and \"g2ding\"."),
                        authors,
                        documenters,
                        translators,
                        about_gnome_ding_logo_pixbuf);
  gtk_widget_set_name (about_gnome_ding, "about_gnome_ding");
  gtk_window_set_destroy_with_parent (GTK_WINDOW (about_gnome_ding), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_gnome_ding, about_gnome_ding, "about_gnome_ding");

  return about_gnome_ding;
}

GtkWidget*
create_preferences1 (void)
{
  GtkWidget *preferences1;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox3;
  GtkWidget *hbox8;
  GtkWidget *image21;
  GtkWidget *label5;
  GtkWidget *hbox5;
  GtkWidget *label6;
  GtkWidget *table1;
  GtkWidget *label10;
  GtkWidget *hbox7;
  GtkWidget *label11;
  GtkWidget *aspell_suggest;
  GtkWidget *label12;
  GtkWidget *aspell_charset;
  GtkWidget *label9;
  GtkWidget *aspell;
  GtkWidget *vbox2;
  GtkWidget *hbox9;
  GtkWidget *image22;
  GtkWidget *label4;
  GtkWidget *hbox6;
  GtkWidget *label7;
  GtkWidget *vbox4;
  GtkWidget *grep_word;
  GtkWidget *grep_case;
  GtkWidget *label8;
  GtkWidget *grep;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  preferences1 = gtk_dialog_new ();
  gtk_widget_set_name (preferences1, "preferences1");
  gtk_window_set_title (GTK_WINDOW (preferences1), _("gnome-ding - preferences"));

  dialog_vbox1 = GTK_DIALOG (preferences1)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 4);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox8, FALSE, FALSE, 4);

  image21 = create_pixmap (preferences1, "gnome-ding/gnome-ding.png");
  gtk_widget_set_name (image21, "image21");
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox8), image21, FALSE, FALSE, 8);

  label5 = gtk_label_new (_("Sellect some settings for use \nwith spellchecking (by aspell)."));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox8), label5, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox5, TRUE, TRUE, 0);

  label6 = gtk_label_new (_(" "));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 4);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox5), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 4);

  label10 = gtk_label_new (_("Charset:"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 4, 4);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label10), 0.98, 0.5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table1), hbox7, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label11 = gtk_label_new (_("<small>(low)</small>"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox7), label11, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  aspell_suggest = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (2, 0, 4, 1, 1, 1)));
  gtk_widget_set_name (aspell_suggest, "aspell_suggest");
  gtk_widget_show (aspell_suggest);
  gtk_box_pack_start (GTK_BOX (hbox7), aspell_suggest, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (aspell_suggest), FALSE);
  gtk_range_set_update_policy (GTK_RANGE (aspell_suggest), GTK_UPDATE_DISCONTINUOUS);

  label12 = gtk_label_new (_("<small>(high)</small>"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  aspell_charset = gtk_entry_new ();
  gtk_widget_set_name (aspell_charset, "aspell_charset");
  gtk_widget_show (aspell_charset);
  gtk_table_attach (GTK_TABLE (table1), aspell_charset, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 4, 4);
  gtk_editable_set_editable (GTK_EDITABLE (aspell_charset), FALSE);
  gtk_entry_set_text (GTK_ENTRY (aspell_charset), _("UTF8"));

  label9 = gtk_label_new (_("Suggestion Mode:"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 4, 4);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label9), 0.98, 0.5);

  aspell = gtk_label_new_with_mnemonic (_("_spellchecker"));
  gtk_widget_set_name (aspell, "aspell");
  gtk_widget_show (aspell);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), aspell);
  gtk_label_set_justify (GTK_LABEL (aspell), GTK_JUSTIFY_LEFT);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 4);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox9, FALSE, FALSE, 4);

  image22 = create_pixmap (preferences1, "gnome-ding/gnome-ding.png");
  gtk_widget_set_name (image22, "image22");
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox9), image22, FALSE, FALSE, 8);

  label4 = gtk_label_new (_("Settings only use for translation (by grep)"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox9), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox6, TRUE, TRUE, 0);

  label7 = gtk_label_new (_(" "));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 4);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox6), vbox4, TRUE, TRUE, 0);

  grep_word = gtk_check_button_new_with_mnemonic (_("search only exact words"));
  gtk_widget_set_name (grep_word, "grep_word");
  gtk_widget_show (grep_word);
  gtk_box_pack_start (GTK_BOX (vbox4), grep_word, TRUE, TRUE, 4);

  grep_case = gtk_check_button_new_with_mnemonic (_("case sensitive"));
  gtk_widget_set_name (grep_case, "grep_case");
  gtk_widget_show (grep_case);
  gtk_box_pack_start (GTK_BOX (vbox4), grep_case, TRUE, TRUE, 4);

  label8 = gtk_label_new (_(" "));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox4), label8, TRUE, TRUE, 4);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  grep = gtk_label_new_with_mnemonic (_("_translation"));
  gtk_widget_set_name (grep, "grep");
  gtk_widget_show (grep);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), grep);
  gtk_label_set_justify (GTK_LABEL (grep), GTK_JUSTIFY_LEFT);

  dialog_action_area1 = GTK_DIALOG (preferences1)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (okbutton1, "okbutton1");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (preferences1), okbutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) preferences1, "close",
                    G_CALLBACK (on_preferences1_close),
                    NULL);
  g_signal_connect ((gpointer) preferences1, "destroy",
                    G_CALLBACK (on_preferences1_destroy),
                    NULL);
  g_signal_connect ((gpointer) aspell_suggest, "value_changed",
                    G_CALLBACK (on_aspell_suggest_value_changed),
                    NULL);
  g_signal_connect ((gpointer) grep_word, "toggled",
                    G_CALLBACK (on_grep_word_toggled),
                    NULL);
  g_signal_connect ((gpointer) grep_case, "toggled",
                    G_CALLBACK (on_grep_case_toggled),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (preferences1, preferences1, "preferences1");
  GLADE_HOOKUP_OBJECT_NO_REF (preferences1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (preferences1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (preferences1, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (preferences1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (preferences1, image21, "image21");
  GLADE_HOOKUP_OBJECT (preferences1, label5, "label5");
  GLADE_HOOKUP_OBJECT (preferences1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (preferences1, label6, "label6");
  GLADE_HOOKUP_OBJECT (preferences1, table1, "table1");
  GLADE_HOOKUP_OBJECT (preferences1, label10, "label10");
  GLADE_HOOKUP_OBJECT (preferences1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (preferences1, label11, "label11");
  GLADE_HOOKUP_OBJECT (preferences1, aspell_suggest, "aspell_suggest");
  GLADE_HOOKUP_OBJECT (preferences1, label12, "label12");
  GLADE_HOOKUP_OBJECT (preferences1, aspell_charset, "aspell_charset");
  GLADE_HOOKUP_OBJECT (preferences1, label9, "label9");
  GLADE_HOOKUP_OBJECT (preferences1, aspell, "aspell");
  GLADE_HOOKUP_OBJECT (preferences1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (preferences1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (preferences1, image22, "image22");
  GLADE_HOOKUP_OBJECT (preferences1, label4, "label4");
  GLADE_HOOKUP_OBJECT (preferences1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (preferences1, label7, "label7");
  GLADE_HOOKUP_OBJECT (preferences1, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (preferences1, grep_word, "grep_word");
  GLADE_HOOKUP_OBJECT (preferences1, grep_case, "grep_case");
  GLADE_HOOKUP_OBJECT (preferences1, label8, "label8");
  GLADE_HOOKUP_OBJECT (preferences1, grep, "grep");
  GLADE_HOOKUP_OBJECT_NO_REF (preferences1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (preferences1, okbutton1, "okbutton1");

  return preferences1;
}

