/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>
#include <gconf/gconf-client.h>

#include "interface.h"
#include "support.h"
#include "main.h"

gint win_x_size = 0;
gint win_y_size = 0;
gint sug_mode = 3;
gboolean hidden = FALSE;
gboolean debug = TRUE;
gchar *trans_de_en = NULL;
gchar *trans_lat_de = NULL;
gchar *thes_de = NULL;

gboolean search_exact_words = TRUE;
gboolean serach_case_sense = TRUE;

gint get_x_size() { return win_x_size; }
gint get_y_size() { return win_y_size; }
gint get_sug_mode() { return sug_mode; }
gboolean  get_debug() { return debug; }
gboolean  get_hidden() { return hidden; }
gboolean  get_search_exact_words() { return search_exact_words; }
gboolean  get_search_case_sense()  { return serach_case_sense; }

gchar *get_trans_de_en() { return trans_de_en; }
gchar *get_trans_lat_de() { return trans_lat_de; }
gchar *get_thes_de() { return thes_de; }

void set_x_size( gint val ) {
	if ( val < 20 ) val = 500;
	win_x_size = val;
}

void set_y_size( gint val ) {
	if ( val < 20 ) val = 500;
	win_y_size = val;
}

void
set_search_exact_words(gboolean value)
{
	/* set word-exactly-search for egrep */
	search_exact_words = value;	
}
void
set_search_case_sense(gboolean value)
{
	/* set case-sensitive for egrep */
	serach_case_sense = value;	
}

void
set_sug_mode(gint value)
{
	/* set suggestion-mode for aspell */
	if (value < 1 ) value = 3;
	if (value > 4 ) value = 3;
	sug_mode = value;
}





int
main (int argc, char *argv[])
{
  GtkWidget *gnome_ding;
  GConfClient *gconf;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  	gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);
 
	
	gconf = gconf_client_get_default ();
    gconf_client_add_dir(gconf, "/apps/gnome-ding", GCONF_CLIENT_PRELOAD_RECURSIVE, NULL);

	win_x_size = gconf_client_get_int (gconf, "/apps/gnome-ding/size_x", NULL);
	if( win_x_size < 20 ) win_x_size = 500;
	win_y_size = gconf_client_get_int (gconf, "/apps/gnome-ding/size_y", NULL);
	if( win_y_size < 20 ) win_y_size = 300;
	hidden = gconf_client_get_bool(gconf, "/apps/gnome-ding/hidden", NULL);
	debug = gconf_client_get_bool(gconf, "/apps/gnome-ding/debug", NULL);
	
	search_exact_words = gconf_client_get_bool(gconf, "/apps/gnome-ding/exact_words", NULL);
	serach_case_sense  = gconf_client_get_bool(gconf, "/apps/gnome-ding/case_sense", NULL);
	
	sug_mode = gconf_client_get_int (gconf, "/apps/gnome-ding/sug_mode", NULL);
	if ( sug_mode < 1 ) sug_mode = 3;
	if ( sug_mode > 4 ) sug_mode = 3;
	
	trans_de_en = gconf_client_get_string( gconf, "/apps/gnome-ding/trans_de_en", NULL);
	if( trans_de_en == NULL ) {
		trans_de_en = g_strdup("/usr/share/dict/ger-eng.ding");	
	}
	trans_lat_de = gconf_client_get_string( gconf, "/apps/gnome-ding/trans_lat_de", NULL);
	if( trans_lat_de == NULL ) {
		trans_lat_de = g_strdup("/usr/share/dict/lat-deu.ding");	
	}
	thes_de = gconf_client_get_string( gconf, "/apps/gnome-ding/thes_de", NULL);
	if( thes_de == NULL ) {
		thes_de = g_strdup("/usr/share/dict/thesaurus-de.ding");	
	}
	
	/* fixme: check, if we can open/exist trans_de_en-file */
	
	
	
	if ( debug == TRUE ) {
		g_print("%s x=%i x=%i\n", _("Read config.."), win_x_size, win_y_size );
	}
 	gnome_ding = create_gnome_ding ();
	on_wordlist_init();
	gtk_window_set_default_size( GTK_WINDOW(gnome_ding), win_x_size , win_y_size );
	gtk_widget_show (gnome_ding);
   
 	fill_combo( gnome_ding );
	
  	gtk_main (); 
	/* GConf destroy */
	if ( get_debug() == TRUE ) {
		g_print("%s\n", _("write config, exit"));
	}
	on_wordlist_delete();
	
	
	
	gconf_client_set_int (gconf, "/apps/gnome-ding/size_x", win_x_size, NULL);
    gconf_client_set_int (gconf, "/apps/gnome-ding/size_y", win_y_size, NULL);
	gconf_client_set_bool(gconf, "/apps/gnome-ding/hidden", hidden, NULL);
	gconf_client_set_bool(gconf, "/apps/gnome-ding/debug",  debug, NULL);
	
	gconf_client_set_bool(gconf, "/apps/gnome-ding/exact_words",  search_exact_words, NULL);
	gconf_client_set_bool(gconf, "/apps/gnome-ding/case_sense",  serach_case_sense, NULL);
	
	gconf_client_set_int (gconf, "/apps/gnome-ding/sug_mode", sug_mode, NULL);
	
	gconf_client_set_string(gconf, "/apps/gnome-ding/trans_de_en", trans_de_en, NULL);
	gconf_client_set_string(gconf, "/apps/gnome-ding/trans_lat_de", trans_lat_de, NULL);
	gconf_client_set_string(gconf, "/apps/gnome-ding/thes_de", thes_de, NULL);
	// todo: last dict
	// todo: remember last setup
	// todo: config dict-path
	
	gconf_client_remove_dir (gconf, "/apps/gnome-ding", NULL);
    g_object_unref (gconf);
	g_free( trans_de_en );
	g_free( trans_lat_de );
  	return 0;
}

